version: '3.9'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./ui:/usr/src/app
    command: sh -c "npm start"
    ports:
      - "3000:3000"
    stdin_open: true 